# -*- coding: utf-8 -*-
"""array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ok6ADZ43iQ-eJGBOPBRI5MhCXz7guYYE
"""

#Append
#adas an element to array
import array as arr
x=arr.array('i',[1,2,3,4,5,6,25,5])
print(x)
x.append(8)
print(x)

#extend
import array as arr
arr=arr.array('i',[1,2,3,4,5,6,25,5])
print(arr)
arr.extend([12,14,11])
print(arr)

#insert(insert the list)
import array as arr
arr=arr.array('i',[1,2,3,4,5,6,25,5])
print(arr)
arr.insert(2,12)
print(arr)

#pop(pop the element)
import array as arr
x=arr.array('i',[1,2,3,4,5,6,25,5])
print(x)
x.pop(2)
print(x)
x.pop(5)
print(x)

#remove(remove occurance)
import array as arr
x=arr.array('i',[1,2,3,4,5,6,25,5])
print(x)
x.remove(5)

x=arr.array('i',[1,2,3,4,5,6,25,5])
def remove_second_occurance(array,value):
  count=0
  for elements in range(len(x)):
    if array[elements]==value:
      count += 1
      if count ==2:
        array.pop(elements)
        break

remove_second_occurance(x,5)
print("array after emoving second occurence of 5:",x)

#count ()

import array as arr
x=arr.array('i',[1,2,3,4,5,6,25,5])
print("original array:",x)
print("count of 5:",x.count(5))

#reverse
x=arr.array('i',[1,2,3,4,5,6,25,5])
print("original array:",x)
x.reverse()
print("reverse array:",x)

#buffer
import array as arr
print("original array:",x)
print(x.buffer_info())

#tolist
import array as arr
x=arr.array('i',[1,2,3,4,5,6,25,5])
print("original array:",x)
print(x.tolist())

